### ISSUE TITLE
Naulinux-extras repo baseurl goes to unexisting location

### ISSUE THREAD

**Issue by scytem** [giggsoff/labsdn#2]
Openvswitch, mininet, ryu, ctapudp, keyworker dependencies unavailable because of incorrect baseurl location and due to the lack of an up-to-date repository with dependencies for work. 

I've created pull request with short-term solution, but the best solution is to fix the remote naulinux repository. You could check it [here](https://github.com/giggsoff/labsdn/pull/1)

Best regards,
student of K42151 group
Kravchenko Artyom

**Comment by giggsoff** [comment]
Please try new version in master branch
https://github.com/giggsoff/labsdn/commit/d6814febc0ec4068e49a40ecbec15d15f78281dd
